### ISSUE TITLE
improvements to `.link` class

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#307]
You can UTF8-encode reusable SVG icons, e.g.

```css
.svgbackground {
  background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><circle cx="300" cy="300" r="150" stroke-width="3" stroke="#f00" fill="#ff0" /></svg>');
}
```
---
Also use drop shadows on external links.
